exclude: 'notebooks/general_assembly_2023'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: mixed-line-ending
- repo: https://github.com/keewis/blackdoc
  rev: v0.3.9
  hooks:
  - id: blackdoc
    additional_dependencies: [black==23.11.0]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
  - id: ruff
    args: [--fix, --show-fixes]
    types_or: [python, pyi, jupyter]
  - id: ruff-format
    types_or: [python, pyi, jupyter]
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --preserve-quotes]
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.19.3
  hooks:
  - id: gitleaks
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.7
  hooks:
  - id: nbqa
    entry: nbqa mdformat
    name: nbqa-mdformat
    alias: nbqa-mdformat
    args: [--nbqa-md]
    additional_dependencies: [mdformat]
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
  - id: nbstripout
    args: [--drop-empty-cells]
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
