name: wp4
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.10
- jupyterlab
- cartopy
- cdsapi
- cfgrib
- cf-units
- dask
- fsspec
- geopandas
- matplotlib
- netCDF4
- pandas
- pip
- plotly
- pydantic
- python-dotenv
- pyyaml
- rich
- sqlalchemy
- typer
- toml
- xarray
- xesmf
- pip:
  - git+https://github.com/bopen/c3s-eqc-automatic-quality-control.git
  - cacholote
  - cads-toolbox
  - cgul
  - emohawk
  - kaleido
