name: ❓ General Issue
description: General issue, that's not a bug report.
labels: [question]
body:
- type: textarea
  id: issue-description
  attributes:
    label: What is your issue?
    description: |
      Please describe your issue.
    required: true

- type: textarea
  id: sample-code
  attributes:
    label: Minimal Complete Verifiable Example
    description: |
      If useful, add a minimal, self-contained copy-pastable example that demonstrates the issue.
      This will be automatically formatted into code, so no need for markdown backticks.
    render: Python

- type: textarea
  id: log-output
  attributes:
    label: Relevant log output
    description: |
      If useful, please copy and paste any relevant output.
      This will be automatically formatted into code, so no need for markdown backticks.
    render: Python

- type: textarea
  id: extra
  attributes:
    label: Anything else we need to know?
    description: |
      Please describe any other information you want to share, such as your WP if you are running on the VM.

- type: textarea
  id: show-versions
  attributes:
    label: Environment
    description: |
      If useful, paste the output of `conda list` between the `<details>` tags, leaving an empty line following the opening tag.
    value: |
      <details>



      </details>
